#!/bin/bash

if [ "$1" == "--CYK" ]
then
    if [ "$2" == "" ]
    then 
        cp ./Demos/CYKDemo CYKDemo
        ./CYKDemo
        rm CYKDemo
    else
        cp ./Demos/CYK_TERM_INPUT CYK_TERM_INPUT
        ./CYK_TERM_INPUT "$2" "$3"
        rm CYK_TERM_INPUT
    fi
        
  
elif [ "$1" == "--TM" ]
then 
  cp ./Demos/TuringMachineDemo TuringMachineDemo
  ./TuringMachineDemo
  rm TuringMachineDemo
  
elif [ "$1" == "--LRParser" ]
 then 
 	cp ./Demos/LRParserDemo LRParserDemo
 	./LRParserDemo "$2" "$3" "$4"
 	rm LRParserDemo

  
elif [ "$1" == "--TMParser" ]
then 
  cp ./Demos/TMParserDemo1 TMParserDemo1
  cp ./Demos/TMParserDemo2 TMParserDemo2
  ./TMParserDemo1
  read -p "Press ENTER to continue " input
  ./TMParserDemo2
  rm TMParserDemo1
  rm TMParserDemo2
  
 elif [ "$1" == "--PDA" ]
 then
 	cp ./Demos/PDAStringDemo PDAStringDemo
 	cp ./Demos/PDATypeDemo PDATypeDemo
 	if [ "$2" == "--type" ]
 	then
 		if [ "$3" == "" ]
 		then
 			./PDATypeDemo "./XML-Files/LR1-1.xml"
 		else
 			./PDATypeDemo "$3"
 		fi
 	elif [ "$2" == "--string" ]
 	then
		./PDAStringDemo "$3" "$4"
 	else
 		echo "Please provide an option [type/string] for the PDADemo."
 	fi
 	rm PDAStringDemo
 	rm PDATypeDemo
 	
 
  
else 
  echo " invalid option"
fi
